- name: update text file
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: shell command to append date to text file
      shell: date +"This file has been updated at %c" >> dumpfile.txt 
